set enc=utf-8       " Encoding UTF-8
set number          " Shows line number
set showmatch       " Show bracket matches
set visualbell      " Disable beep, only visual bell
set hlsearch        " Highlight all search matches
set smartcase       " Pay attention to case when caps
set ignorecase      " Ignore case when search
set incsearch       " Show search results when typing
set hidden          " Allows to change buffer without saving
set timeout timeoutlen=5000 ttimeoutlen=100 " Fixes lag on shift+O
"" Indention settings
set autoindent      " Sets same indention on new line
set expandtab       " Use spaces, not tabs
set ts=4            " Set indent 4 spaces
set shiftwidth=4    " How much to indent using >>
set softtabstop=4   " Affects tab press

set ruler
set colorcolumn=79  " Vertical ruler, PEP8 helper
set undolevels=1000 " Steps of undo
set backspace=indent,eol,start
set relativenumber  " Changes line nr to relatives
set cursorline      " Hilight current line
set nocompatible    " Remove compatibility with vi
set path+=**        " Better find
set wildmenu        " Display all matching files
set laststatus=2    " File path in status
set t_Co=256        " 256 colors
set clipboard=unnamed " Make yank copy to global clipboard
set list lcs=trail:·,tab:»· " Prettier white space characters
let mapleader = "," " Sets map leader

" Vim swap files and backups directory
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Flake8 remap
autocmd FileType python map <Leader>c :call Flake8()<CR>

colorscheme Monokai " Sets colorscheme

"" Code coloring and indention base ond filetype
syntax on
filetype indent on
filetype plugin on

" Airline
let g:airline_powerline_fonts=1 " Uses powerline fonts
let g:airline#extensions#branch#enabled=1 " Shows current branch
let g:airline#extensions#tabline#enabled = 1 " Show buffers in tabs
" Hide banner on edit file browser
let g:netrw_banner=0

" vim plug
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'edkolev/tmuxline.vim'
Plug 'tpope/vim-fugitive'
Plug 'nvie/vim-flake8'
call plug#end()

